DROP DATABASE IF EXISTS EMS;

CREATE DATABASE EMS;
USE EMS;

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DEPARTMENT_NAME VARCHAR(25) NOT NULL
);

CREATE TABLE EMPLOYEES(
EMPID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(45),
LASTNAME VARCHAR(45),
DOB VARCHAR(10),
EMAIL VARCHAR(100),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID )
);

CREATE TABLE LOGIN_MASTER(
EMPID INT NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(30) NOT NULL,
ROLE VARCHAR(20) NOT NULL,
FOREIGN KEY (EMPID) REFERENCES EMPLOYEES(EMPID)
);

CREATE TABLE COMPLIANCE(
COMPLIANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
RL_TYPE VARCHAR(15),
DETAILS VARCHAR(250),
CREATE_DATE DATE,
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID )
);

CREATE TABLE STATUSREPORT(
COMPLIANCE_ID INT NOT NULL ,
STATUS_REPORT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMPID INT NOT NULL,
COMMENTS VARCHAR(15),
CREATE_DATE DATE,
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID),
FOREIGN KEY (EMPID) REFERENCES EMPLOYEES (EMPID),
FOREIGN KEY (COMPLIANCE_ID) REFERENCES COMPLIANCE (COMPLIANCE_ID)
);

INSERT INTO `ems`.`department` (`DEPARTMENT_ID`, `DEPARTMENT_NAME`) VALUES ('1', 'IT');
INSERT INTO `ems`.`department` (`DEPARTMENT_ID`, `DEPARTMENT_NAME`) VALUES ('2', 'HR');

INSERT INTO `ems`.`employees` (`EMPID`, `FIRSTNAME`, `LASTNAME`, `DOB`, `EMAIL`, `DEPARTMENT_ID`) VALUES ('1010', 'Krunal', 'Patel', '1993-12-02', 'krunal@gmail.com', '1');
INSERT INTO `ems`.`employees` (`EMPID`, `FIRSTNAME`, `LASTNAME`, `DOB`, `EMAIL`, `DEPARTMENT_ID`) VALUES ('1020', 'Vernon', 'D\'Souza', '1993-10-06', 'vernon@gmail.com', '2');

INSERT INTO `ems`.`login_master` (`EMPID`, `PASSWORD`, `ROLE`) VALUES ('1010', 'abc123', 'admin');
INSERT INTO `ems`.`login_master` (`EMPID`, `PASSWORD`, `ROLE`) VALUES ('1020', 'abc123', 'user');
